Patch capnp libkj to fix build with GCC 9
Fixes errors like this:

```
.../ep_capnp/c++/src/kj/main.c++:690:38:   required from here
.../x86_64-conda-linux-gnu/include/c++/9.3.0/bits/stl_tree.h:780:8: error: static assertion failed: comparison object must be invocable as const
  780 |        is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [src/kj/CMakeFiles/kj.dir/main.c++.o] Error 1
make[4]: *** [src/kj/CMakeFiles/kj.dir/all] Error 2
```